- name: Verifica se o Docker está rodando
  become: true
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Garante que o diretório prometheus existe
  ansible.builtin.file:
    path: /home/ubuntu/prometheus
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Gera o prometheus.yml com base no template
  ansible.builtin.template:
    src: templates/prometheus.yml.j2
    dest: /home/ubuntu/prometheus/prometheus.yml
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Create docker-compose.yaml
  template:
    src: "templates/docker-compose.yml.j2"
    dest: "/home/ubuntu/docker-compose.yml"
    mode: "644"

- name: Remove docker services
  community.docker.docker_compose_v2:
    project_src: "/home/ubuntu/"
    state: absent
    remove_orphans: true

- name: Start projects containers
  community.docker.docker_compose_v2:
    project_src: "/home/ubuntu/"
    state: present
    wait: true
    check_files_existing: true
    remove_orphans: true
    recreate: "always"
    wait_timeout: 180
