# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/commons

- name: Atualizar cache de pacotes
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Instalar pacotes essenciais
  ansible.builtin.apt:
    name:
      - curl
      - git
      - unzip
      - python3-pip
    state: present

- name: Instalar Docker (via script oficial)
  ansible.builtin.shell: |
    curl -fsSL https://get.docker.com | sh
  args:
    creates: /usr/bin/docker

- name: Reiniciar serviço Docker
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Adicionar usuário atual ao grupo docker
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Verificar se docker-compose já está instalado
  ansible.builtin.stat:
    path: /usr/local/bin/docker-compose
  register: compose_bin

- name: Instalar Docker Compose
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  when: not compose_bin.stat.exists