---
- name: Setup VMS
  hosts: all
  become: true
  roles:
    - commons

- name: Configurar servidor da aplicação
  hosts: application
  become: true
  roles:
    - flask_app

- name: Configurar servidor de monitoramento
  hosts: monitoring
  become: true
  roles:
    - monitoring